Disable thinking mode for Step1X multi-image support
- Remove --thinking flag from GPU scripts
- Thinking mode doesn't support list of images
- Fixes AttributeError: 'list' object has no attribute 'convert'
- Step1X will run in standard mode for WinoBias experiment